// Mock AI service - no API key needed
const getMockResponse = (prompt: string, persona?: string): string => {
  // Return mock responses for fun
  if (persona === 'mamdami') {
    return "My brother, the vibes are off the charts! The swagger is strong with this one. Let's discuss this over some Diet Coke in the Subway VIP lounge. The energy of the city demands it!";
  }
  if (persona === 'bibi') {
    return "Categorically, this is an existential threat that requires immediate attention. I have prepared a diagram with a red line. We need to discuss this over lunch. Can I borrow a drone for the weekend?";
  }
  if (persona === 'kim') {
    return "My best friend! The big button is ready. Do you have new movies on DVD? Also, Dennis Rodman says hello. The rocket is very powerful, just like our friendship!";
  }
  return "AI feature unavailable - this is a mock demo!";
};

export const summarizeEmail = async (emailBody: string): Promise<string> => {
  // Mock summary - no API needed
  const lines = emailBody.split('\n').filter(l => l.trim().length > 0);
  return `• ${lines[0]?.substring(0, 60)}...\n• Key points from the email\n• Action items or follow-up needed`;
};

export const draftEmailReply = async (
  originalEmailBody: string, 
  tone: 'professional' | 'casual' | 'brief',
  instructions: string
): Promise<string> => {
  // Mock draft - no API needed
  return `Thank you for your email regarding: ${instructions.substring(0, 50)}...

This is a mock AI draft. In a real implementation, this would be generated by AI.

Best regards`;
};

// NEW: Thinking Mode for Complex Tasks
export const draftComplexReply = async (instructions: string): Promise<string> => {
  // Mock complex draft - no API needed
  return `After careful consideration of: ${instructions.substring(0, 50)}...

This is a mock complex AI response. In a real implementation, this would use advanced AI thinking capabilities.

Best regards`;
};

export const polishEmailDraft = async (draft: string): Promise<string> => {
    // Mock polish - just return the draft as-is (or add some basic formatting)
    return draft.trim() + '\n\n[Polished by mock AI]';
};

// NEW: Image Generation
export const generateEmailImage = async (prompt: string, size: '1K' | '2K' | '4K'): Promise<string | null> => {
  // Mock image generation - return null (no API needed)
  console.log(`Mock: Would generate image for "${prompt}" at ${size} resolution`);
  return null;
};

// NEW: Search Grounding
export const researchTopic = async (query: string): Promise<{ text: string; sources: {title: string, uri: string}[] }> => {
  // Mock research - no API needed
  return {
    text: `Mock research results for: ${query.substring(0, 50)}... This is a demo feature.`,
    sources: [
      { title: "Example Source 1", uri: "https://example.com" },
      { title: "Example Source 2", uri: "https://example.com" }
    ]
  };
};

export const generateMamdamiReply = async (userEmailBody: string): Promise<string> => {
    // Mock Mamdami reply - no API needed
    const replies = [
        "My brother, the vibes are off the charts! The swagger is strong with this one. Let's discuss this over some Diet Coke in the Subway VIP lounge. The energy of the city demands it!",
        "King, I hear you loud and clear. The establishment is trying to hold us back, but we're building equity here. The nightlife is calling, and so is this opportunity. Let's make it happen!",
        "Boss, the people are speaking, and they want action. I've got the red carpet ready, but we need to navigate some bureaucratic hurdles first. The subway is waiting, my friend!"
    ];
    return replies[Math.floor(Math.random() * replies.length)];
};

export const generateBibiReply = async (userEmailBody: string): Promise<string> => {
    // Mock Bibi reply - no API needed
    const replies = [
        "Categorically, this is an existential threat that requires immediate attention. I have prepared a diagram with a red line. We need to discuss this over lunch. Can I borrow a drone for the weekend?",
        "Donald, history will judge us on this moment. I've drawn up a chart showing the red line. This is bigger than lunch - it's about our shared destiny. Also, do you have any spare space lasers?",
        "My friend, the red line has been crossed. I cannot confirm or deny the details, but I can tell you this: we need more diagrams. And possibly a laser pointer. The hummus situation is critical."
    ];
    return replies[Math.floor(Math.random() * replies.length)];
};

export const generateKimReply = async (userEmailBody: string): Promise<string> => {
    // Mock Kim reply - no API needed
    const replies = [
        "My best friend! The big button is ready. Do you have new movies on DVD? Also, Dennis Rodman says hello. The rocket is very powerful, just like our friendship!",
        "Dotard... I mean, my friend! The rocket is pointing at the sky, which is good. Can you send me some Chicago Bulls highlights? And maybe some Elton John CDs?",
        "The system has been launched! I mean, I read your email. My rocket is bigger than your rocket. But we are still friends. Do you have Netflix password?"
    ];
    return replies[Math.floor(Math.random() * replies.length)];
};